services:
  redisDB:
    image: redis:latest
    container_name: redis_test
    command: redis-server --appendonly yes
    platform: linux/amd64
    volumes:
      - redisDB:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  postgresDB:
    image: postgres:latest
    container_name: postgres_test
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - postgresDB:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:4.0.3-management
    container_name: rabbit_test
    platform: linux/amd64
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  postgresDB:
    driver: local
  redisDB:
    driver: local